<img src="https://github.com/milena-seismo/DSB-Unit-02/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Exercise: descriptive statistics in `pandas`

_Authors: David Asboth_

---

## Learning Objectives

After this lesson, students will be able to:

- Explore descriptive statistics of a data set using pandas

# Lesson Guide

This notebook helps students practice:

- Calculating descriptive statistics in `pandas`
- Doing group-level analysis in `pandas`
    - Doing "split-apply-combine" with `groupby`
    - Aggregating and summarizing data

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

The question we want to answer is: **How do LEGO products vary across different types/themes?**

## Guided questions

***Remember to check back to notebooks 1 and 2 - they contain everything you need!***

Let's import the data and preview it.

*Note: if you place the `lego.csv` file in the same folder as this notebook, you'll need to change the filepath to just `"lego.csv"`*

In [2]:
import pandas as pd

lego = pd.read_csv("https://raw.githubusercontent.com/milena-seismo/DSB-Unit-02/refs/heads/main/data/lego.csv")
lego.head()

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN

In [2]:
lego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Packaging         14936 non-null  object
 8   Num_Instructions  14936 non-null  int64
 9   Availability      14936 non-null  object
 10  Pieces            13133 non-null  float64
 11  Minifigures       7686 non-null   float64
 12  Owned             14771 non-null  float64
 13  Rating            14936 non-null  float64
 14  USD_MSRP          5837 non-null   float64
 15  Total_Quantity    12276 non-null  float64
 16  Current_Price     5442 non-null   float64
dtypes: float64(7), int64(2), object(8)
memory usage: 1.9+ MB

#### 1. Find the "theme group" that has the biggest sets, i.e. that has the highest average number of pieces

In [3]:
lego["Theme_Group"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 14936 entries, 0 to 14935
Series name: Theme_Group
Non-Null Count  Dtype
--------------  -----
14915 non-null  object
dtypes: object(1)
memory usage: 116.8+ KB

In [4]:
lego["Theme_Group"].head(10)

0    Pre-school
1    Pre-school
2    Pre-school
3    Pre-school
4       Vintage
5    Modern day
6    Modern day
7    Modern day
8    Modern day
9    Modern day
Name: Theme_Group, dtype: object

In [5]:
lego["Theme_Group"].sort_values(ascending=False)

87       Vintage
81       Vintage
97       Vintage
96       Vintage
94       Vintage
          ...
14780        NaN
14781        NaN
14782        NaN
14783        NaN
14784        NaN
Name: Theme_Group, Length: 14936, dtype: object

In [11]:
lego["Theme_Group"].sort_values()

11992    Action/Adventure
8484     Action/Adventure
9765     Action/Adventure
9764     Action/Adventure
8485     Action/Adventure
               ...
14780                 NaN
14781                 NaN
14782                 NaN
14783                 NaN
14784                 NaN
Name: Theme_Group, Length: 14936, dtype: object

In [12]:
lego.groupby("Theme_Group")["Pieces"].describe()

,count,mean,std,min,25%,50%,75%,max
Theme_Group,,,,,,,,
Action/Adventure,1156.0,264.974913,383.571668,1.0,47.00,138.0,360.00,6163.0
Art and crafts,94.0,775.276596,1543.739716,33.0,84.00,253.5,616.00,11695.0
Basic,813.0,242.610086,361.608996,1.0,25.00,84.0,334.00,2847.0
Constraction,491.0,103.167006,129.729580,2.0,30.00,53.0,116.00,856.0
Educational,396.0,350.780303,555.026463,1.0,30.00,122.5,397.50,4900.0
Girls,238.0,62.752101,64.711446,1.0,16.00,48.0,81.75,450.0
Historical,468.0,168.645299,229.132911,3.0,25.00,68.0,210.25,1601.0
Junior,225.0,64.231111,69.098467,1.0,14.00,41.0,97.00,480.0
Licensed,1952.0,391.485143,583.496094,0.0,93.00,232.5,471.25,7541.0
Miscellaneous,1917.0,98.004695,296.432826,0.0,6.00,13.0,68.00,4502.0
Model making,712.0,598.648876,1008.749522,6.0,68.00,258.0,689.00,10001.0
Modern day,2212.0,218.909584,259.676532,1.0,40.00,119.5,301.00,2010.0
Pre-school,1470.0,35.025170,40.600480,1.0,9.00,22.0,48.00,640.0
Racing,270.0,176.414815,251.066554,1.0,35.00,77.5,197.50,1484.0
Technical,588.0,446.646259,625.730473,0.0,59.25,214.5,591.00,4108.0
Vintage,114.0,163.017544,187.454820,17.0,47.25,94.5,211.75,1112.0

In [19]:
lego_mean = lego.groupby("Theme_Group")["Pieces"].mean()
lego_mean.sort_values(ascending=False)

Theme_Group
Art and crafts      775.276596
Model making        598.648876
Technical           446.646259
Licensed            391.485143
Educational         350.780303
Action/Adventure    264.974913
Basic               242.610086
Modern day          218.909584
Racing              176.414815
Historical          168.645299
Vintage             163.017544
Constraction        103.167006
Miscellaneous        98.004695
Junior               64.231111
Girls                62.752101
Pre-school           35.025170
Name: Pieces, dtype: float64

In [5]:
lego.groupby("Theme_Group")["Pieces"].mean()

Theme_Group
Action/Adventure    264.974913
Art and crafts      775.276596
Basic               242.610086
Constraction        103.167006
Educational         350.780303
Girls                62.752101
Historical          168.645299
Junior               64.231111
Licensed            391.485143
Miscellaneous        98.004695
Model making        598.648876
Modern day          218.909584
Pre-school           35.025170
Racing              176.414815
Technical           446.646259
Vintage             163.017544
Name: Pieces, dtype: float64

In [6]:
lego_mean = lego.groupby("Theme_Group")["Pieces"].mean()
lego_mean.sort_values(ascending=False)

Theme_Group
Art and crafts      775.276596
Model making        598.648876
Technical           446.646259
Licensed            391.485143
Educational         350.780303
Action/Adventure    264.974913
Basic               242.610086
Modern day          218.909584
Racing              176.414815
Historical          168.645299
Vintage             163.017544
Constraction        103.167006
Miscellaneous        98.004695
Junior               64.231111
Girls                62.752101
Pre-school           35.025170
Name: Pieces, dtype: float64

In [7]:
lego_mean = lego.groupby("Theme_Group")["Pieces"].mean()

In [8]:
lego_mean

Theme_Group
Action/Adventure    264.974913
Art and crafts      775.276596
Basic               242.610086
Constraction        103.167006
Educational         350.780303
Girls                62.752101
Historical          168.645299
Junior               64.231111
Licensed            391.485143
Miscellaneous        98.004695
Model making        598.648876
Modern day          218.909584
Pre-school           35.025170
Racing              176.414815
Technical           446.646259
Vintage             163.017544
Name: Pieces, dtype: float64

In [10]:
lego_mean.describe()

count     16.000000
mean     260.036844
std      207.524700
min       35.025170
25%      101.876428
50%      197.662199
75%      360.956513
max      775.276596
Name: Pieces, dtype: float64

#### 2. How does that group compare to the average number of pieces in the entire data set?

In [20]:
lego_mean = lego.groupby("Theme_Group")["Pieces"].mean()
lego_mean.sort_values(ascending=False)

Theme_Group
Art and crafts      775.276596
Model making        598.648876
Technical           446.646259
Licensed            391.485143
Educational         350.780303
Action/Adventure    264.974913
Basic               242.610086
Modern day          218.909584
Racing              176.414815
Historical          168.645299
Vintage             163.017544
Constraction        103.167006
Miscellaneous        98.004695
Junior               64.231111
Girls                62.752101
Pre-school           35.025170
Name: Pieces, dtype: float64

#### 3. Within this theme group, how does the number of pieces compare per individual theme?

*Hint: you'll need to filter your data before doing the aggregation!*

In [21]:
lego_mean = lego.groupby("Theme_Group")["Pieces"]

In [22]:
lego_mean.head(10)

0         16.0
1         20.0
2         21.0
3         32.0
4        330.0
         ...
13097    110.0
13152     33.0
13153     33.0
13154     33.0
13155     33.0
Name: Pieces, Length: 160, dtype: float64

In [24]:
lego_mean.agg(["min", "max"])

                   min      max
Theme_Group
Action/Adventure   1.0   6163.0
Art and crafts    33.0  11695.0
Basic              1.0   2847.0
Constraction       2.0    856.0
Educational        1.0   4900.0
Girls              1.0    450.0
Historical         3.0   1601.0
Junior             1.0    480.0
Licensed           0.0   7541.0
Miscellaneous      0.0   4502.0
Model making       6.0  10001.0
Modern day         1.0   2010.0
Pre-school         1.0    640.0
Racing             1.0   1484.0
Technical          0.0   4108.0
Vintage           17.0   1112.0

In [31]:
lego_mean.agg(["max"])

                      max
Theme_Group
Action/Adventure   6163.0
Art and crafts    11695.0
Basic              2847.0
Constraction        856.0
Educational        4900.0
Girls               450.0
Historical         1601.0
Junior              480.0
Licensed           7541.0
Miscellaneous      4502.0
Model making      10001.0
Modern day         2010.0
Pre-school          640.0
Racing             1484.0
Technical          4108.0
Vintage            1112.0

In [39]:
lego_max = lego_mean.agg(["max"])
lego_max.describe()

                max
count     16.000000
mean    3774.375000
std     3507.935611
min      450.000000
25%     1048.000000
50%     2428.500000
75%     5215.750000
max    11695.000000

In [42]:

print(f'Max of pieces:{lego_max}')

Max of pieces:                      max
Theme_Group
Action/Adventure   6163.0
Art and crafts    11695.0
Basic              2847.0
Constraction        856.0
Educational        4900.0
Girls               450.0
Historical         1601.0
Junior              480.0
Licensed           7541.0
Miscellaneous      4502.0
Model making      10001.0
Modern day         2010.0
Pre-school          640.0
Racing             1484.0
Technical          4108.0
Vintage            1112.0

head#### 4. Find the most expensive set in the "Creator Expert" theme

#### 5. BONUS - can you figure out the average price AND the maximum number of pieces for each **theme group** in a single command?

*Hint: look at the `.agg` command...*

## Reflection

Based on your initial findings, what answers can you give to the initial business question?

> **How do LEGO products vary across different types/themes?**